<#
.SYNOPSIS
    Refactored script that:
      1) Imports a list of computers from CSV (ComputerFQDN, IpAddress, LastLoggedInUser).
      2) Imports AD Subnets from AD_Subnets.csv and converts them to numeric ranges for IP matching.
      3) Runs in parallel (PowerShell 7+) with a controlled throttle limit.
      4) Queries a Global Catalog using specified credentials (instead of random DCs or NetBIOS).
      5) Outputs a consolidated CSV.

.DESCRIPTION
    This script shows how to:
      - Prompt for AD credentials up front (Get-Credential).
      - Use ForEach-Object -Parallel with a -ThrottleLimit to avoid overloading the environment.
      - Match a computer’s IP to an AD site by comparing numeric IP addresses to subnets.
      - Look up the computer object in AD via a GC.
      - Optionally look up the last-logged-in user in AD via the GC as well.
      - Write results to a final CSV file.

.NOTES
    - Requires PowerShell 7+ to use parallel processing features.
    - Adjust $GCServer to your environment’s GC FQDN (and port if needed).
    - Ensure your account/credentials have read access across the forest.

.PARAMETER ComputerCsvPath
    Path to the Computers.csv file (ComputerFQDN, IpAddress, LastLoggedInUser).

.PARAMETER SubnetsCsvPath
    Path to the AD_Subnets.csv file (generated by get_subnets.ps1).

.PARAMETER OutputCsvPath
    Where to store the final results (optional).

.PARAMETER GCServer
    The Global Catalog server FQDN or FQDN:Port (e.g., "gc1.domain.local" or "gc1.domain.local:3268").

.PARAMETER ThrottleLimit
    How many parallel tasks to run at once.

.EXAMPLE
    # Example usage:
    .\Find-ComputerLocation.ps1 `
      -ComputerCsvPath 'C:\temp\Computers.csv' `
      -SubnetsCsvPath 'C:\temp\AD_Subnets.csv' `
      -OutputCsvPath 'C:\temp\Results.csv' `
      -GCServer 'GC01.domain.local:3268' `
      -ThrottleLimit 10
#>

param(
    [string]$ComputerCsvPath = "C:\temp\Computers.csv",
    [string]$SubnetsCsvPath  = "C:\temp\AD_Subnets.csv",
    [string]$OutputCsvPath   = "C:\temp\FinalResults.csv",
    [string]$GCServer        = "<YOUR GC SERVER>:3268",  # Adjust to your environment
    [int]$ThrottleLimit      = 10
)

################################################################################
# Prompt for credentials once at script start
################################################################################
Write-Host "Please enter credentials with read access to the GC..."
$Cred = Get-Credential

################################################################################
# Helper Functions for IP-to-Subnet Logic
################################################################################

function ConvertTo-UInt32Ip {
    <#
    .SYNOPSIS
        Converts a dotted-decimal IPv4 address (e.g. "10.10.10.5") to a [uint32] number.
    #>
    param(
        [Parameter(Mandatory)]
        [ValidatePattern('^(\d{1,3}\.){3}\d{1,3}$')]
        [string]$IpAddress
    )
    $octets = $IpAddress.Split('.')
    return [uint32](($octets[0] -shl 24) -bor
                    ($octets[1] -shl 16) -bor
                    ($octets[2] -shl 8)  -bor
                     $octets[3])
}

function ConvertCidrToRange {
    <#
    .SYNOPSIS
        Converts a CIDR notation (e.g. "10.10.10.0/24") into a hashtable containing
        Network (lowest IP) and Broadcast (highest IP) in [uint32] form.
    #>
    param(
        [Parameter(Mandatory)]
        [ValidatePattern('^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$')]
        [string]$Cidr
    )

    try {
        # Split the CIDR into the IP address and prefix
        $parts  = $Cidr.Split('/')
        $netIp  = $parts[0]
        $prefix = [int]$parts[1]

        # Convert the network IP to a uint32
        $netNum = ConvertTo-UInt32Ip -IpAddress $netIp

        # Generate the subnet mask based on the prefix
        $mask   = [uint32](0xFFFFFFFF -shl (32 - $prefix))

        # Apply the bitwise NOT operation (Preserved from original version)
        $maskInt = [int32]$mask
        $maskNot = [uint32]([math]::Pow(2, 32) - 1 - $maskInt)

        # Calculate the network and broadcast addresses
        $network   = $netNum -band $mask
        $broadcast = $network -bor $maskNot

        # Return the result as a hashtable
        return @{
            Network   = $network
            Broadcast = $broadcast
            Prefix    = $prefix
        }
    }
    catch {
        # Handle any errors and provide a meaningful message
        Write-Error "Failed to convert CIDR '$Cidr': $($_.Exception.Message)"
        return $null
    }
}


function Test-IpInRange {
    <#
    .SYNOPSIS
        Checks if a given IP (uint32) is between Network and Broadcast (inclusive).
    #>
    param(
        [Parameter(Mandatory)][uint32]$IpNum,
        [Parameter(Mandatory)][uint32]$Network,
        [Parameter(Mandatory)][uint32]$Broadcast
    )
    return ($IpNum -ge $Network -and $IpNum -le $Broadcast)
}


################################################################################
# 1) Import and Prepare AD Subnets
################################################################################

if (-not (Test-Path $SubnetsCsvPath)) {
    Write-Error "Subnets CSV '$SubnetsCsvPath' not found."
    return
}

Write-Host "`n[Info] Importing AD Subnets from $SubnetsCsvPath"
$adSubnets = Import-Csv -Path $SubnetsCsvPath

foreach ($row in $adSubnets) {
    if ($row.Subnet -match '/') {
        try {
            $range = ConvertCidrToRange -Cidr $row.Subnet
            $row | Add-Member -NotePropertyName 'NetworkNum'   -NotePropertyValue $range.Network -Force
            $row | Add-Member -NotePropertyName 'BroadcastNum' -NotePropertyValue $range.Broadcast -Force
        }
        catch {
            Write-Warning "Failed to parse subnet $($row.Subnet): $($_.Exception.Message)"
            $row | Add-Member -NotePropertyName 'NetworkNum'   -NotePropertyValue $null -Force
            $row | Add-Member -NotePropertyName 'BroadcastNum' -NotePropertyValue $null -Force
        }
    }
    else {
        Write-Warning "Subnet '$($row.Subnet)' not in CIDR format. Skipping range logic."
        $row | Add-Member -NotePropertyName 'NetworkNum'   -NotePropertyValue $null -Force
        $row | Add-Member -NotePropertyName 'BroadcastNum' -NotePropertyValue $null -Force
    }
}


################################################################################
# 2) Import Computers CSV
################################################################################

if (-not (Test-Path $ComputerCsvPath)) {
    Write-Error "Computers CSV '$ComputerCsvPath' not found."
    return
}

Write-Host "`n[Info] Importing computers from $ComputerCsvPath"
$computers = Import-Csv -Path $ComputerCsvPath

if (-not $computers) {
    Write-Warning "No records found in $ComputerCsvPath. Exiting."
    return
}


################################################################################
# 3) Process in Parallel
################################################################################

Write-Host "`n[Info] Processing $($computers.Count) computers in parallel with ThrottleLimit=$ThrottleLimit..."

# This will hold the final results
$results = $computers | ForEach-Object -Parallel {

    # Region: Local Helper Functions
    function ConvertTo-UInt32Ip {
        param(
            [Parameter(Mandatory)]
            [ValidatePattern('^(\d{1,3}\.){3}\d{1,3}$')]
            [string]$IpAddress
        )
        $octets = $IpAddress.Split('.')
        return [uint32](($octets[0] -shl 24) -bor
                        ($octets[1] -shl 16) -bor
                        ($octets[2] -shl 8)  -bor
                         $octets[3])
    }

    function Test-IpInRange {
        param(
            [Parameter(Mandatory)][uint32]$IpNum,
            [Parameter(Mandatory)][uint32]$Network,
            [Parameter(Mandatory)][uint32]$Broadcast
        )
        return ($IpNum -ge $Network -and $IpNum -le $Broadcast)
    }

    # Local references to parameters from the parent scope
    $ipAddress        = $PSItem.IpAddress
    $computerFQDN     = $PSItem.ComputerFQDN
    $lastLoggedInUser = $PSItem.LastLoggedInUser

    Write-Host "[Parallel] Processing $computerFQDN - IP: $ipAddress"

    # 1) Match IP to an AD site
    $siteName = "Unknown"
    if ($ipAddress -match '^(\d{1,3}\.){3}\d{1,3}$') {
        $ipNum = ConvertTo-UInt32Ip -IpAddress $ipAddress

        foreach ($netRow in $using:adSubnets) {
            if ($netRow.NetworkNum -and $netRow.BroadcastNum) {
                if (Test-IpInRange -IpNum $ipNum -Network $netRow.NetworkNum -Broadcast $netRow.BroadcastNum) {
                    $siteName = $netRow.SiteName
                    break
                }
            }
        }
    }

    # 2) Query AD (via GC) for the computer object
    $adComputer = $null
    $computerOU = $null
    $operatingSystem = $null
    $lastLogonDate   = $null
    if ($computerFQDN) {
        $shortName = $computerFQDN.Split(".")[0]

        try {
            # Attempt exact FQDN match in GC
            $adComputer = Get-ADComputer `
                -Server $using:GCServer `
                -Credential $using:Cred `
                -Filter "DNSHostName -eq '$computerFQDN'" `
                -Properties OperatingSystem, LastLogonDate, CanonicalName `
                -SearchScope Subtree  # ensuring we check entire GC

            if (-not $adComputer) {
                # Fallback to short name if FQDN didn't match
                $adComputer = Get-ADComputer `
                    -Server $using:GCServer `
                    -Credential $using:Cred `
                    -Filter "Name -eq '$shortName'" `
                    -Properties OperatingSystem, LastLogonDate, CanonicalName `
                    -SearchScope Subtree
            }

            if ($adComputer) {
                $computerOU      = $adComputer.CanonicalName
                $operatingSystem = $adComputer.OperatingSystem
                $lastLogonDate   = $adComputer.LastLogonDate
            }
        }
        catch {
            Write-Warning "[Parallel] Error querying GC for ${computerFQDN}: $($_.Exception.Message)"
        }
    }

    # 3) (Optional) Query AD (via GC) for the last logged in user
    #    We'll do a simple Identity lookup. If they're in a different domain, the GC should find them if everything is in the forest.
    $adUser = $null
    if ($lastLoggedInUser) {
        $candidate = $null
        if ($lastLoggedInUser -match '\\') {
            # domain\user
            $parts = $lastLoggedInUser.Split('\')
            $candidate = "$($parts[0])\$($parts[1])"
        }
        elseif ($lastLoggedInUser -match '@') {
            # user@domain.local
            $candidate = $lastLoggedInUser
        }
        else {
            $candidate = $lastLoggedInUser
        }

        try {
            $adUser = Get-ADUser `
                -Server $using:GCServer `
                -Credential $using:Cred `
                -Identity $candidate `
                -Properties DisplayName, Department, EmailAddress `
                -SearchScope Subtree `
                -ErrorAction SilentlyContinue
        }
        catch {
            Write-Warning "[Parallel] Error searching for user ${lastLoggedInUser}: $($_.Exception.Message)"
        }
    }

    # 4) Build the result object
    [PSCustomObject]@{
        ComputerFQDN      = $computerFQDN
        IpAddress         = $ipAddress
        AD_Site           = $siteName
        ComputerOU        = $computerOU
        OperatingSystem   = $operatingSystem
        LastLogonDate     = $lastLogonDate
        LastLoggedInUser  = $lastLoggedInUser
        UserSamAccount    = $adUser?.SamAccountName
        UserDisplayName   = $adUser?.DisplayName
        UserDepartment    = $adUser?.Department
    }

} -ThrottleLimit $ThrottleLimit

################################################################################
# 4) Output and Save Results
################################################################################

Write-Host "`n[Info] Parallel processing complete. We have $($results.Count) results."

# Display in console
$results | Format-Table -AutoSize

# Export to CSV
if ($OutputCsvPath) {
    Write-Host "[Info] Exporting results to $OutputCsvPath"
    $results | Export-Csv -Path $OutputCsvPath -NoTypeInformation
}
Write-Host "[Info] Done."
